# Change the name here to the name of your own workers
name = "onout-chatgpt-telegram-workers"
compatibility_date = "2023-04-14"
main = "./dist/index.js"
workers_dev = true
minify = true
send_metrics = false

kv_namespaces = [
  { binding = "DATABASE", id = "" }
]

[vars]

# More parameters in README.md.
# Parameters without comments are required.
# The option that writes the parameter is the default value of the parameter.
# All variables must be strings, and the values of multiple parameters are separated by commas.

# Basic configuration
API_KEY = ""
TELEGRAM_AVAILABLE_TOKENS = ""
CHAT_WHITE_LIST = ""
# I_AM_A_GENEROUS_PERSON = "false"
# AUTO_TRIM_HISTORY = "false"
# MAX_HISTORY_LENGTH = "20"
# DEBUG_MODE = "false"
# CHAT_MODEL = "gpt-3.5-turbo"
# SYSTEM_INIT_MESSAGE = ""

# Group related configuration
# GROUP_CHAT_BOT_ENABLE = "true"
# TELEGRAM_BOT_NAME = ""
# GROUP_CHAT_BOT_SHARE_MODE = "false"
# CHAT_GROUP_WHITE_LIST = "false"

# Payment
# AMOUNT_OF_FREE_MESSAGES=3
# ACTIVATION_CODE = ""
# LINK_TO_PAY_FOR_CODE = ""